apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    # 可以自行設定
    type: api
  namespace: argocd
  name: service
spec:
  destination:
    name: Production
    namespace: service-namespace
    server: ''
  source:
    path: deploy/k8s/helm/application
    repoURL: >-
      https://application.deploy-repository.git
    targetRevision: master
    helm:
      valueFiles:
        - values-production.yaml
  project: production
  syncPolicy:
    # 如果要啟用自動同步
    # automated:
    #   prune: true
    #   selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    # 避免 HPA 調整 POD 數量時，讓 ArgoCD 呈現 OutOfSync
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    # 避免 Rollout 調整 istio 路由時，讓 ArgoCD 呈現 OutOfSync
    - group: networking.istio.io
      kind: VirtualService
      jsonPointers:
        - /spec/http/0