apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ (print .Values.service "-ingress-stable") | lower | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ (print .Release.Namespace "/" .Values.ingress.host ) }}
    http:
      paths:
      - path: {{ .Values.ingress.path ) }}
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ (print .Values.service "-stable") | lower | quote }}
          servicePort: 8080