# Default values for {$ServiceName}.
# This is a YAML-formatted file.

# The overall system your service is a part of
# This Value is used by Label: app.kubernetes.io/part-of
system: {$ServiceName}

# The name of your service
# This Value is used by Label: 
#     1. app.kubernetes.io/name
#     2. app
# This Value is used by Docker Container: 
#     1. name
# This Value is Named to kubernetes kind:
#     1. Service
#     2. DestinationRule
#     3. Gateway (service name-gateway)
#     4. VisualService (service name-vs)
#     5. HorizontalPodAutoscaler
#     6. Deployment
#     7. PodDisruptionBudget
service: {$ServiceName}

# The major version number for your service
version: 1

# Istio Ingress Gateway
# 這是 Istio 預設的 LoadBalance Gateway Selector Label name，與範本檔案中的 gateway.yaml 所設定的 Gateway 是不一樣的服務
# 這個服務等同於 Kubernetes Ingress
istioIngressGateway: "ingressgateway"

# Docker settings
image:
  # The name of your docker container
  repository: {$image-repo}
  # Your docker container's tag
  tag: default-tag
  imagePullPolicy: IfNotPresent

# Istio uses the service account name as a component of the service's security
# identity. Set "create" to false to use an previously created service account.
serviceAccount:
  name: {$ServiceName}-sa
  create: true

# The initial number of pod replicas to run for your service
replicaCount: 1
# The maximum number of pods from that set that can be unavailable at once
maxUnavailable: 1

# Horizontal pod autoscaler configuration (optional)
autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetAverageCpuUtilization: 95

# Port settings
# Ports must be named <protocol>[-<suffix>] to work with Istio.
# Valid protocols are grpc, http, http2, https, mongo, mysql, redis, tcp, tls, udp
ports:
  - name: grpc-svc
    port: 8443
    targetPort: 443
  - name: http-status
    port: 8080
    targetPort: 80

# VisualService 中的 http 內部 http request 設定
# httpHeaders:
#   request:
#     set:
#       # 在 Header 上面加入被 Gateway 複寫掉的 url 資訊，主要是讓服務內部組完整 URL 的時候可以組出正確的網址
#       # (不是所有服務都需要)
#       proxy-removed-prefix: "/"
#       # 加入此 Header 設定 XForwardedProto (不是所有服務都需要)
#       x-forwarded-proto: https

# Configure the Istio ingress gateway to route outside traffic for the provided
# host name to this service on the ports and protocols defined in the 'ports' section 
# above. 
istioGateway:
  name: {$ServiceName}-gateway
  host: {$ServiceDomain}
  matchPrefix: 
    - "/"
  # 如果服務沒有自己的 Domain，而是藉由 Gateway 判定 prefix 的話，會需要加上這個
  uriRewrite: "/"

# The overall timeout for requests to this service
# Optional
overallTimeout: 30s

# Client retry settings (use Istio syntax)
# Optional
retries:
  attempts: 3
  perTryTimeout: 10s

# Circuit breaker settings (use Istio syntax)
# Optional
outlierDetection: 
  consecutive5xxErrors: 5

# Resource settings (use Kubernetes syntax)
# Optional
resources:
  requests:
    memory: "400Mi"
    cpu: "200m"
  limits:
    memory: "800Mi"
    cpu: "250m"

# Probe settings (use Kubernetes syntax)
# Optional
probes:
  livenessProbe:
    timeoutSeconds: 10
    httpGet:
      path: /health
      port: 80
  readinessProbe:
    timeoutSeconds: 10
    httpGet:
      path: /health
      port: 80

# 設定容器執行時的參數
env:
  # 時區資訊
  LANG: "zh-TW.UTF-8"
  TZ: "Asia/Taipei"
  # .net 執行環境
  ASPNETCORE_ENVIRONMENT: "Release"
  # Exceptionless 相關資料，此處設定的資料會覆蓋掉 appsettings 內的設定
  # Exceptionless__ApiKey: "--"
  # Exceptionless__Enabled: "true"
  # Exceptionless__ServerUrl: "http://exceptionless.example.com.tw"